// <auto-generated />
using System;
using MercadoLp2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MercadoLp2.Migrations
{
    [DbContext(typeof(MercadoLp2Context))]
    [Migration("20190402192119_AtualizacaoBanco")]
    partial class AtualizacaoBanco
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MercadoLp2.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.Property<double>("Preco");

                    b.Property<int>("Qtde");

                    b.HasKey("Id");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("MercadoLp2.Models.ProdutosVendidos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ProdId");

                    b.Property<int>("Qtde");

                    b.Property<int?>("RegistroVendasId");

                    b.Property<double>("preco");

                    b.HasKey("Id");

                    b.HasIndex("ProdId");

                    b.HasIndex("RegistroVendasId");

                    b.ToTable("ProdutosVendidos");
                });

            modelBuilder.Entity("MercadoLp2.Models.RegistroVendas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Data");

                    b.Property<int>("Status");

                    b.Property<int>("Valor");

                    b.HasKey("Id");

                    b.ToTable("RegistroVendas");
                });

            modelBuilder.Entity("MercadoLp2.Models.ProdutosVendidos", b =>
                {
                    b.HasOne("MercadoLp2.Models.Produto", "Prod")
                        .WithMany()
                        .HasForeignKey("ProdId");

                    b.HasOne("MercadoLp2.Models.RegistroVendas")
                        .WithMany("Vendidos")
                        .HasForeignKey("RegistroVendasId");
                });
#pragma warning restore 612, 618
        }
    }
}
